<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.18" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.18" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.4.1" />
    <PackageReference Include="AvaloniaEdit.TextMate" Version="11.4.1" />
    <PackageReference Include="TextMateSharp.Grammars" Version="2.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SharpPad.Engine/SharpPad.Engine.csproj" />
  </ItemGroup>
</Project>
