using System.Security.Cryptography;
using System.Text;

namespace SharpPad.Engine;

/// <summary>
/// Turns a script into a real net10.0 console project so MSBuild/NuGet do all
/// reference resolution. The generated Program.cs is the user code with
/// directive lines blanked, so diagnostics map 1:1 to editor lines.
/// </summary>
public static class ProjectGenerator
{
    /// <summary>Version pins for DB support injected when #connection is used.
    /// Keep in sync with SharpPad.Runtime.csproj.</summary>
    private static readonly Dictionary<string, string> ProviderPackages = new()
    {
        ["sqlite"] = """<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />""",
        ["postgres"] = """<PackageReference Include="Npgsql" Version="10.0.3" />""",
        ["sqlserver"] = """<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />""",
        ["mysql"] = """<PackageReference Include="MySqlConnector" Version="2.6.1" />"""
    };

    public static string BuildDirFor(string scriptKey)
    {
        var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(scriptKey)))[..16];
        var dir = Path.Combine(Workspace.BuildDir, hash);
        Directory.CreateDirectory(dir);
        return dir;
    }

    /// <param name="runtimeDllPath">Path to the built SharpPad.Runtime.dll shipped next to the app.</param>
    /// <param name="connection">Resolved connection, when the script has a #connection directive.</param>
    public static void Generate(string dir, ScriptDocument doc, string runtimeDllPath, DbConnectionInfo? connection)
    {
        var packages = new StringBuilder();
        foreach (var n in doc.NugetRefs)
        {
            packages.Append("    <PackageReference Include=\"").Append(n.Package).Append('"');
            if (n.Version is not null) packages.Append(" Version=\"").Append(n.Version).Append('"');
            else packages.Append(" Version=\"*\"");
            packages.AppendLine(" />");
        }
        if (connection is not null)
        {
            packages.AppendLine("    <PackageReference Include=\"Dapper\" Version=\"2.1.79\" />");
            if (ProviderPackages.TryGetValue(connection.Provider, out var pkg))
                packages.Append("    ").AppendLine(pkg);
        }

        var dllRefs = new StringBuilder();
        foreach (var path in doc.DllRefs)
        {
            var name = Path.GetFileNameWithoutExtension(path);
            dllRefs.AppendLine($"""
                    <Reference Include="{name}">
                      <HintPath>{path}</HintPath>
                    </Reference>
                """);
        }

        File.WriteAllText(Path.Combine(dir, "script.csproj"), $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>disable</ImplicitUsings>
                <LangVersion>latest</LangVersion>
                <AssemblyName>script</AssemblyName>
                <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
                <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
                <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
              </PropertyGroup>
              <ItemGroup>
            {packages}    <Reference Include="SharpPad.Runtime">
                  <HintPath>{runtimeDllPath}</HintPath>
                </Reference>
            {dllRefs}  </ItemGroup>
            </Project>
            """);

        File.WriteAllText(Path.Combine(dir, "GlobalUsings.cs"), $"""
            // <auto-generated/>
            global using System;
            global using System.Collections;
            global using System.Collections.Generic;
            global using System.IO;
            global using System.Linq;
            global using System.Net.Http;
            global using System.Text;
            global using System.Threading;
            global using System.Threading.Tasks;
            global using SharpPad.Runtime;
            {(connection is not null ? "global using static SharpPad.Runtime.Db;" : "")}
            """);

        var dbInit = connection is not null
            ? $"SharpPad.Runtime.Db.Init({Quote(connection.Provider)}, {Quote(connection.ConnectionString)});"
            : "";
        File.WriteAllText(Path.Combine(dir, "Bootstrap.g.cs"), $$"""
            // <auto-generated/>
            static class __SharpPadBootstrap
            {
                [System.Runtime.CompilerServices.ModuleInitializer]
                internal static void Init()
                {
                    SharpPad.Runtime.Protocol.Init();
                    {{dbInit}}
                }
            }
            """);

        File.WriteAllText(Path.Combine(dir, "Program.cs"), doc.CodeForCompilation);
    }

    private static string Quote(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
